# This is a Docker Compose file for a web service
services:
  web:
    build: .  # Build the image from the current directory
    ports:
      - "8000:8000"  # Map host port 80 to container port 8000
    environment:
      # Set environment variables from the host environment
      - STARK_PRIVATE_KEY_VALUE=${STARK_PRIVATE_KEY_VALUE}
      - STARK_PROJECT_ID=${STARK_PROJECT_ID}  
    volumes:
      - ./private_key.pem:/app/private_key.pem:ro
    restart: always  # Always restart the container if it stops
  
  nginx:
    image: nginx:stable  # Use the official Nginx image
    ports:
      - "443:443"  # Map host port 80 to container port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
